version: '2'
services:
    jhipsterexample-mysql:
        container_name: jhipsterexample-mysql
        image: mysql:5.7.13
        # volumes:
        #     - ~/volumes/jhipster/jHipsterExample/mysql/:/var/lib/mysql/
        environment:
            - MYSQL_USER=root
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=jhipsterexample
            - MYSQL_PASSWORD=loaduser5
        ports:
            - 3306:3306
        command: mysqld --lower_case_table_names=1 --skip-ssl
